name: aiyoubErsteWorkflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job_1: 
    runs-on: ubuntu-latest
    steps:
      - name: AiyoubErsteSchritt
        run: echo "Hallo Suheib, Hallo Marian"

      - name: Abschied
        run: echo "Bye Bye!"

zweiter-job:
    runs-on: ubuntu-latest
    needs: changed-job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Datum anzeigen
        run: date       